paths:
  /auth/login:
    post:
      description: Login endpoint
      tags:
        - Public
      requestBody:
        description: User credentials (email, password)
        content:
          application/json:
            examples:
              Credentials exmaple:
                value:
                  mail: pp@pp.com
                  pass: pp
            schema:
              type: object
              properties:
                mail:
                  type: string
                pass:
                  type: string
      responses:
        200:
          description: Ok