paths:
  /users/:
    get:
      summary: Get all users
      tags:
        - Users
    post:
      summary: Create
      tags:
        - Users
      requestBody:
        description: User data
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                username:
                  type: string
                password:
                  type: string
            examples:
              Credentials exmaple:
                value:
                  mail: pp@pp.com
                  username: Paco
                  password: 123
      responses:
        200:
          description: Ok
  /users/{id}:
    delete:
      summary: Delete user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
      responses:
        200:
          description: Ok
    get:
      summary: Get user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          examples: 
            a:
              value: 1
              summary: Le pasamos un 1
      responses:
        200:
          description: Ok
    put:
      summary: Update
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          examples: 
            a:
              value: 1
      requestBody:
        description: User data
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                username:
                  type: string
                password:
                  type: string
            examples:
              Credentials exmaple:
                value:
                  mail: aa@aa.com
                  username: Paco
                  password: 456
      responses:
        200:
          description: Ok   
  /users/login:
    post:
      summary: login
      description: Login endpoint
      tags:
        - Users
      requestBody:
        description: User credentials (email, password)
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                password:
                  type: string
            examples:
              Credentials exmaple:
                value:
                  mail: pp@pp.com
                  password: 123
      responses:
        200:
          description: Ok
  /users/restricted-path:
    get:
      description: Restricted path
      tags:
        - Users
      responses:
        200:
          description: Ok
