paths:
  /users/restricted-path:
    get:
      description: Restricted path
      tags:
        - Users
      responses:
        200:
          description: Ok

  /users/create:
    post:
      description: Create a new user
      tags:
        - Users
      requestBody:
        description: User data
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                pass:
                  type: string
    tags:
      - Public
    responses:
      200:
        description: Ok

  /users/{id}:
    delete:
      description: Delete user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
      responses:
        200:
          description: Ok

    patch:
      description: Delete user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
      requestBody:
        description: User data
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Ok
